import { defineConfig } from "vitest/config";

// These suites exercise schemas and pure domain policy. Keeping their canonical
// file list here lets the Node and Workers pools stay disjoint without moving
// tests away from the domain files they cover.
export const NODE_UNIT_TEST_FILES = [
  "tests/access-control-role-id-contract.test.ts",
  "tests/access-control-schema.test.ts",
  "tests/admin-identity.test.ts",
  "tests/calendar-timezone.test.ts",
  "tests/csv.test.ts",
  "tests/db-json-membership.test.ts",
  "tests/db-pagination.test.ts",
  "tests/db-query-budget.test.ts",
  "tests/db-search.test.ts",
  "tests/db-sort.test.ts",
  "tests/donation-badge.test.ts",
  "tests/download-disposition.test.ts",
  "tests/email-attachments.test.ts",
  "tests/email-campaign-custom.test.ts",
  "tests/email-markdown-escape.test.ts",
  "tests/email-template-engine.test.ts",
  "tests/event-email-campaign-token.test.ts",
  "tests/event-invite-preview-token.test.ts",
  "tests/event-registration-status-policy.test.ts",
  "tests/form-answers.test.ts",
  "tests/form-field-rules.test.ts",
  "tests/form-submission-window.test.ts",
  "tests/gravatar-download.test.ts",
  "tests/image-upload.test.ts",
  "tests/links-schema.test.ts",
  "tests/management-links.test.ts",
  "tests/member-applications-schema.test.ts",
  "tests/membership-category-selection-schema.test.ts",
  "tests/og-badge-hero-image.test.ts",
  "tests/og-badge-http.test.ts",
  "tests/og-badge-prerender-image.test.ts",
  "tests/og-card-rendering.test.ts",
  "tests/og-image-type.test.ts",
  "tests/openapi-route-validation.test.ts",
  "tests/pagination-sort-schema.test.ts",
  "tests/proposal-access-paths.test.ts",
  "tests/proposal-route-policy.test.ts",
  "tests/provider-failure-safety.test.ts",
  "tests/security-primitives.test.ts",
  "tests/scheduled-job-runner.test.ts",
  "tests/server-collection-controller.test.ts",
  "tests/session-policy.test.ts",
  "tests/shared-schema-composition.test.ts",
  "tests/slug.test.ts",
  "tests/stripe-webhook-signature.test.ts",
  "tests/timezone-utils.test.ts",
  "tests/timezone.test.ts",
  "tests/url-schemas.test.ts",
  "tests/vote-consultation-tally.test.ts",
  "tests/vote-derived-status.test.ts",
  "tests/vote-tally-policy.test.ts",
  "tests/votes-schema.test.ts",
];

export default defineConfig({
  test: {
    include: [...NODE_UNIT_TEST_FILES],
    exclude: ["**/._*"],
    environment: "node",
    reporters: ["default", "./tests/tools/slowest-tests-reporter.ts"],
  },
});
