import { astroMarkdownWorkerPlugin } from "./scripts/lib/astro-markdown-worker-plugin.mjs";
import { publicationEnvironment, wranglerEnvironment } from "./scripts/publication/build-context.mjs";
import { workersPreviewBaseUrl } from "./scripts/lib/workers-preview-url.mjs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { cloudflare } from "@cloudflare/vite-plugin";
import { defineConfig } from "vite";
import { contentMediaPlugin } from "./scripts/lib/content-media-plugin.mjs";
import { bylinesPlugin } from "./scripts/lib/bylines-plugin.mjs";
import { trustListPlugin } from "./scripts/lib/trust-list-plugin.mjs";

const projectRoot = fileURLToPath(new URL(".", import.meta.url));

export default defineConfig(() => {
  // The Cloudflare plugin selects the Wrangler environment. A preview build
  // emits the production Worker config, whose previews block binds preview resources.
  process.env.CLOUDFLARE_ENV = wranglerEnvironment(publicationEnvironment());

  // Links generated by a branch Preview point at that Preview, not the
  // preview fallback in wrangler.jsonc. Only previews.vars changes.
  const previewBaseUrl = workersPreviewBaseUrl(process.env.WORKERS_CI_BRANCH);
  if (previewBaseUrl) console.log(`Preview APP_BASE_URL set to ${previewBaseUrl}`);

  return {
    clearScreen: false,
    esbuild: {
      jsx: "automatic" as const,
      jsxImportSource: "preact",
    },
    publicDir: resolve(projectRoot, "public"),
    resolve: {
      alias: {
        react: "preact/compat",
        "react-dom/test-utils": "preact/test-utils",
        "react-dom": "preact/compat",
        "react/jsx-dev-runtime": "preact/jsx-runtime",
        "react/jsx-runtime": "preact/jsx-runtime",
      },
    },
    server: {
      host: "0.0.0.0",
      port: 8788,
      strictPort: true,
      watch: { ignored: ["**/dist/**"] },
    },
    preview: {
      host: "0.0.0.0",
      port: 8788,
      strictPort: true,
    },
    plugins: [
      astroMarkdownWorkerPlugin(),
      contentMediaPlugin(projectRoot),
      trustListPlugin(projectRoot),
      bylinesPlugin(projectRoot),
      cloudflare(previewBaseUrl ? { config: { previews: { vars: { APP_BASE_URL: previewBaseUrl } } } } : {}),
    ],
  };
});
