import { Hono } from "hono";
import { fromHono } from "chanfana";
import { finalizeApiResponse, onRequest as middleware_l } from "./_middleware";
import { handleError } from "../../_lib/http";
import { GeolocationCountryGet, onRequest as GeolocationCountryGet_l } from "./geolocation/country";
import { RouteGet } from "./index";
import analytics_Router from "./analytics/router";
import auditLog_Router from "./audit-log/router";
import auth_Router from "./auth/router";
import calendar_Router from "./calendar/router";
import donations_Router from "./donations/router";
import email_Router from "./email/router";
import events_Router from "./events/router";
import forms_Router from "./forms/router";
import groups_Router from "./groups/router";
import invites_Router from "./invites/router";
import leadership_Router from "./leadership/router";
import meetings_Router from "./meetings/router";
import membership_Router from "./membership/router";
import members_Router from "./members/router";
import organizations_Router from "./organizations/router";
import retention_Router from "./retention/router";
import scheduler_Router from "./scheduler/router";
import permissions_Router from "./permissions/router";
import proposals_Router from "./proposals/router";
import registrations_Router from "./registrations/router";
import roles_Router from "./roles/router";
import sponsors_Router from "./sponsors/router";
import users_Router from "./users/router";
import votes_Router from "./votes/router";

const app = new Hono();
export const openapi = fromHono(app);

app.onError((error, c) => {
  const request = c.req.raw;
  const requestId =
    ((c as any).get("requestId") as string | undefined) ?? request.headers.get("x-request-id") ?? crypto.randomUUID();
  const sensitive = (c as any).get("sensitive") === true;
  return finalizeApiResponse(request, handleError(error), sensitive, requestId);
});
app.use("*", middleware_l);
openapi.get("/geolocation/country", GeolocationCountryGet);
app.on("HEAD", "/geolocation/country", GeolocationCountryGet_l);
openapi.get("/", RouteGet);
openapi.route("/analytics", analytics_Router);
openapi.route("/audit-log", auditLog_Router);
openapi.route("/auth", auth_Router);
openapi.route("/calendar", calendar_Router);
openapi.route("/donations", donations_Router);
openapi.route("/email", email_Router);
openapi.route("/events", events_Router);
openapi.route("/forms", forms_Router);
openapi.route("/groups", groups_Router);
openapi.route("/invites", invites_Router);
openapi.route("/leadership", leadership_Router);
openapi.route("/meetings", meetings_Router);
openapi.route("/membership", membership_Router);
openapi.route("/members", members_Router);
openapi.route("/organizations", organizations_Router);
openapi.route("/retention", retention_Router);
openapi.route("/scheduler", scheduler_Router);
openapi.route("/permissions", permissions_Router);
openapi.route("/proposals", proposals_Router);
openapi.route("/registrations", registrations_Router);
openapi.route("/roles", roles_Router);
openapi.route("/sponsors", sponsors_Router);
openapi.route("/users", users_Router);
openapi.route("/votes", votes_Router);

export default openapi;
