const featurePaths = {
  payment: ["/donate/"],
  assessment: ["/wg/pkimm/assessment/", "/wg/pkimm/1.0.0/tools/self-assessment/"],
  questions: ["/questions"],
} as const;

/** The same allowlist protects native static responses and Worker-rendered shells. */
export function siteContentSecurityPolicy(pathname = "/"): string {
  const payment = featurePaths.payment.some((path) => pathname.startsWith(path));
  const assessment = featurePaths.assessment.some((path) => pathname.startsWith(path));
  const questions = featurePaths.questions.some((path) => pathname.startsWith(path));
  const script = ["'self'", "'wasm-unsafe-eval'", "https://challenges.cloudflare.com"];
  const connect = ["'self'"];
  const images = ["'self'", "data:", "https://i.ytimg.com"];
  const frames = [
    "https://challenges.cloudflare.com",
    "https://www.youtube-nocookie.com",
    "https://www.youtube.com",
    "https://player.vimeo.com",
  ];
  if (questions) connect.push("https://docs.google.com/spreadsheets/d/");
  if (payment) {
    // Embedded Checkout, Stripe.js, redirects, and Link; restricted to donation pages.
    script.push("https://js.stripe.com", "https://*.js.stripe.com", "https://checkout.stripe.com");
    connect.push("https://api.stripe.com", "https://checkout.stripe.com", "https://link.com", "https://*.link.com");
    frames.push(
      "https://js.stripe.com",
      "https://*.js.stripe.com",
      "https://hooks.stripe.com",
      "https://checkout.stripe.com",
      "https://link.com",
      "https://*.link.com",
    );
    images.push("https://*.stripe.com", "https://*.link.com");
  }
  return [
    "default-src 'none'",
    "base-uri 'none'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    `script-src ${script.join(" ")}`,
    "script-src-attr 'none'",
    "style-src 'self'",
    // The released assessment SDK injects 41 stylesheets. Their hash list exceeds
    // Cloudflare's 2,000-character header line limit. Keep this exception local
    // to the assessment; inline script and style attributes remain forbidden.
    ...(assessment ? ["style-src-elem 'self' 'unsafe-inline'"] : []),
    "style-src-attr 'none'",
    "font-src 'self'",
    `connect-src ${connect.join(" ")}`,
    `img-src ${images.join(" ")}`,
    `frame-src ${frames.join(" ")}`,
    "worker-src 'self' blob:",
    "media-src 'self' https://www.rovid.nl/def/dco/2016/def-dco-20160823-idoa9bivg-web-hd.mp4",
  ].join("; ");
}

export function siteSecurityHeaders(pathname = "/") {
  return {
    "Content-Security-Policy": siteContentSecurityPolicy(pathname),
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Strict-Transport-Security": "max-age=31536000",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=(), browsing-topics=()",
  };
}

/** Generate Cloudflare's native header file without maintaining another policy copy. */
export function siteStaticHeaders(): string {
  const global = Object.entries(siteSecurityHeaders())
    .map(([name, value]) => `    ${name}: ${value}`)
    .join("\n");
  const features = Object.values(featurePaths)
    .flat()
    .map(
      (path) =>
        `${path}*\n    ! Content-Security-Policy\n    Content-Security-Policy: ${siteContentSecurityPolicy(path)}`,
    )
    .join("\n\n");
  return `# Generated by scripts/generate-site-security-headers.mjs.\n\nhttps://:project.pages.dev/*\n    X-Robots-Tag: noindex\n\n/*\n${global}\n\n${features}\n\n/meetings/join/*\n    ! Cache-Control\n    Cache-Control: no-store, max-age=0\n    ! Referrer-Policy\n    Referrer-Policy: no-referrer\n    X-Robots-Tag: noindex, nofollow, noarchive\n\n/m/*\n    ! Cache-Control\n    Cache-Control: no-store, max-age=0\n    ! Referrer-Policy\n    Referrer-Policy: no-referrer\n    X-Robots-Tag: noindex, nofollow, noarchive\n\n/js/built/*\n    ! Cache-Control\n    Cache-Control: public, max-age=31536000, immutable\n`;
}
