-- Migration 0049: `member_since` column for members
--
-- data/members/*.yaml's `memberSince` key (how long an organization or
-- individual has been a PKIC member) had nowhere real to land: the
-- migration script never read it, and the Interim Admin Tool's
-- "Add organization" form already collects a `memberSince` date from staff
-- but silently drops it — there is no column to write it to, so every
-- org/individual's public/self-service "member since" value has actually
-- just been `members.created_at` (the D1 row's insert time, not the real
-- historical join date).
--
-- One column, on `members` — the aggregate row already exists for both
-- org-tied and org-less members (migration 0000), so there is no separate
-- `organizations.member_since` to keep in sync with it. Read paths fall
-- back to `members.created_at` when unset (pre-existing rows, or a caller
-- that doesn't supply one).
ALTER TABLE members ADD COLUMN member_since TEXT;
