/**
 * Quote a value as a SQLite string literal, or NULL when there is no value.
 *
 * Absent values render as `NULL` rather than the four-character string
 * `'null'`, which is what stringifying them produces and is never what a
 * caller means by a missing column.
 */
export function sqlString(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replaceAll("'", "''")}'`;
}

/** The current instant, in the ISO-8601 UTC form every column stores. */
export const NOW = "strftime('%Y-%m-%dT%H:%M:%fZ','now')";

/** A fresh row id, generated by SQLite so a statement needs no binding. */
export const RANDOM_ID = "lower(hex(randomblob(16)))";

/** Render optional text as either a trimmed SQLite string literal or NULL. */
export function toSqlNullableText(value) {
  if (value === null || value === undefined) return "NULL";
  const text = String(value).trim();
  return text.length === 0 ? "NULL" : sqlString(text);
}

/** Preserve non-empty seed values verbatim while treating blank text as NULL. */
export function toSqlNullableTextPreservingWhitespace(value) {
  if (value === null || value === undefined || String(value).trim().length === 0) return "NULL";
  return sqlString(value);
}
