export const E2E_ADMIN_SCOPES: readonly [
  "default",
  "admin-verification",
  "browser-auth",
  "browser-presentation",
  "browser-waitlist",
  "meeting-guest",
  "portal-event",
  "portal-event-management",
  "portal-event-attendee-management",
  "portal-event-invitations",
  "portal-event-proposals",
  "portal-access-control",
  "portal-analytics",
  "portal-donations",
  "portal-email-templates",
  "portal-leadership",
  "portal-mailing-lists",
  "portal-organizations",
  "portal-users",
  "portal-system-operations",
  "portal-membership-settings",
  "portal-membership-form",
  "portal-application-stages",
  "portal-join-categories",
  "portal-member-access",
  "portal-permission-boundaries",
  "portal-identity-security",
  "portal-identity-history",
  "portal-identity-logout",
  "portal-mobile-navigation",
  "portal-dual-capacity",
  "portal-dual-capacity-guard",
  "portal-system-audit-list",
  "portal-system-audit-states",
  "sponsor-workspace",
  "votes",
];

export type E2eAdminScope = (typeof E2E_ADMIN_SCOPES)[number];

export function formatE2eAdminEmail(scope: E2eAdminScope, workerIndex: number): string;
export function e2eAdminEmailsForWorkerCount(workerCount: number): string[];
