export const E2E_ADMIN_SCOPES: readonly [
  "default",
  "scanner-recovery-owner",
  "scanner-recovery-other",
  "portal-agenda-accepted-placement",
  "portal-agenda-preview",
  "portal-agenda-list-readonly",
  "portal-agenda-publication-layout",
  "portal-agenda-staffing-roster",
  "portal-agenda-platform",
  "portal-agenda-public-calendar",
  "portal-agenda-staffing",
  "portal-agenda-track-demand",
  "portal-agenda-transfer-review",
  "portal-agenda-transfer-cli",
  "portal-appearance-overrides",
  "portal-login-layout-expiry",
  "portal-offline-attendance",
  "portal-responsive-widths",
  "portal-responsive-navigation",
  "portal-sponsor-leads",
  "promotion-registration-attribution",
  "portal-session-presentation",
  "portal-management-verification",
  "browser-auth",
  "browser-presentation",
  "browser-historical-mapping-review",
  "browser-historical-mapping-speaker",
  "browser-waitlist",
  "meeting-guest",
  "portal-event",
  "portal-event-management",
  "portal-event-attendee-management",
  "portal-event-proposals",
  "portal-analytics",
  "portal-leadership",
  "portal-group-leadership",
  "public-members-signed-in",
  "portal-mailing-lists",
  "portal-organizations",
  "portal-user-record-self",
  "portal-user-create",
  "portal-users-role-management",
  "portal-user-headshot",
  "meeting-participant-links",
  "portal-members-roll",
  // Never signed in as: a pool identity is a bare `users` row with no
  // membership, which is exactly the starting state a grant needs.
  "portal-members-roll-target",
  "portal-join-existing-organization",
  "portal-sponsor-filters",
  "portal-sponsor-tier-pricing",
  "portal-membership-settings",
  "membership-workflows",
  "membership-workflows-categories",
  "membership-workflows-archive",
  "membership-workflows-breadcrumbs",
  "membership-workflows-payment-only",
  "membership-workflows-staff-review-payment",
  "membership-review-access",
  "group-mailing-sync",
  "portal-membership-form",
  "portal-application-stages-approval",
  "portal-application-stages-decline",
  "portal-application-stages-communications",
  "portal-join-categories",
  "portal-member-access",
  "portal-permission-boundaries",
  "portal-identity-security",
  "portal-identity-history",
  "portal-identity-logout",
  "portal-mobile-navigation",
  "portal-dark-theme",
  "portal-appearance",
  "portal-dual-capacity",
  "portal-dual-capacity-guard",
  "portal-vote-participation",
  "portal-vote-replacement",
  "portal-vote-election",
  "portal-vote-window",
  "portal-vote-eligibility",
  "portal-proposal-states",
  "portal-proposal-states-rejected",
  "proposal-speaker-identity",
  "portal-colleague-self-service",
  "portal-group-self-service",
  "portal-sign-in-return-path",
  "portal-passkeys",
  "portal-personas-provisioning",
  "portal-persona-interested",
  "portal-persona-voting",
  "portal-persona-reader",
  "sponsor-workspace",
  "votes",
];

export type E2eAdminScope = (typeof E2E_ADMIN_SCOPES)[number];

export const E2E_WORKER_COUNT: number;

export function formatE2eAdminEmail(scope: E2eAdminScope, workerIndex: number): string;
export function e2eAdminEmailsForWorkerCount(workerCount: number): string[];
