export const E2E_ADMIN_SCOPES: readonly [
  "default",
  "portal-management-verification",
  "browser-auth",
  "browser-presentation",
  "browser-waitlist",
  "meeting-guest",
  "portal-event",
  "portal-event-management",
  "portal-event-attendee-management",
  "portal-event-invitations",
  "portal-event-proposals",
  "portal-access-control",
  "portal-analytics",
  "portal-donations",
  "portal-email-templates",
  "portal-leadership",
  "portal-mailing-lists",
  "portal-organizations",
  "portal-organizations-representatives",
  "portal-organizations-users-view",
  "portal-organizations-profile",
  "portal-organizations-logo",
  "portal-user-record-self",
  "portal-users",
  "portal-system-operations",
  "portal-membership-settings",
  "portal-membership-form",
  "portal-application-stages",
  "portal-join-categories",
  "portal-member-access",
  "portal-permission-boundaries",
  "portal-identity-security",
  "portal-identity-history",
  "portal-identity-logout",
  "portal-mobile-navigation",
  "portal-dark-theme",
  "portal-appearance",
  "portal-dual-capacity",
  "portal-dual-capacity-guard",
  "portal-vote-participation",
  "portal-vote-replacement",
  "portal-vote-election",
  "portal-vote-window",
  "portal-vote-eligibility",
  "portal-proposal-states",
  "portal-proposal-states-rejected",
  "portal-colleague-self-service",
  "portal-group-self-service",
  "portal-sign-in-return-path",
  "portal-passkeys",
  "portal-personas-provisioning",
  "portal-persona-interested",
  "portal-persona-voting",
  "portal-persona-reader",
  "portal-system-audit-list",
  "portal-system-audit-states",
  "sponsor-workspace",
  "votes",
];

export type E2eAdminScope = (typeof E2E_ADMIN_SCOPES)[number];

export const E2E_WORKER_COUNT: number;

export function formatE2eAdminEmail(scope: E2eAdminScope, workerIndex: number): string;
export function e2eAdminEmailsForWorkerCount(workerCount: number): string[];
