/* eslint-disable */
// This file is generated by scripts/generate-worker-routes.mjs.
// Do not edit by hand.

import type { RouteModule } from "./types";

import * as routeModule1 from "../api/v1/admin/email-templates/preview";
import * as routeModule2 from "../api/v1/admin/events/sync-from-hugo";
import * as routeModule3 from "../api/v1/internal/email/reset-failed";
import * as routeModule4 from "../api/v1/admin/donations/promoters";
import * as routeModule5 from "../api/v1/admin/auth/request-link";
import * as routeModule6 from "../api/v1/admin/auth/verify-link";
import * as routeModule7 from "../api/v1/internal/calendar/rsvp";
import * as routeModule8 from "../api/v1/internal/reminders/run";
import * as routeModule9 from "../api/v1/internal/retention/run";
import * as routeModule10 from "../api/v1/admin/donations/sync";
import * as routeModule11 from "../api/v1/internal/email/retry";
import * as routeModule12 from "../api/v1/admin/email/outbox";
import * as routeModule13 from "../api/v1/internal/jobs/run";
import * as routeModule14 from "../api/v1/admin/email-templates";
import * as routeModule15 from "../api/v1/donations/checkout";
import * as routeModule16 from "../api/v1/donations/promoter";
import * as routeModule17 from "../api/v1/donations/session";
import * as routeModule18 from "../api/v1/admin/donations";
import * as routeModule19 from "../api/v1/webhooks/stripe";
import * as routeModule20 from "../api/v1/admin/events";
import * as routeModule21 from "../api/v1/admin/stats";
import * as routeModule22 from "../api/v1/admin/users";
import * as routeModule23 from "../api/v1/geo";
import * as routeModule24 from "../api/v1/index";
import * as routeModule25 from "../api/index";
import * as routeModule26 from "../api/v1/admin/events/[eventSlug]/invites/attendees/preview";
import * as routeModule27 from "../api/v1/admin/events/[eventSlug]/emails/campaign/preview";
import * as routeModule28 from "../api/v1/admin/events/[eventSlug]/invites/attendees/bulk";
import * as routeModule29 from "../api/v1/admin/events/[eventSlug]/invites/speakers/bulk";
import * as routeModule30 from "../api/v1/admin/events/[eventSlug]/emails/campaign/send";
import * as routeModule31 from "../api/v1/admin/events/[eventSlug]/waitlist/promote";
import * as routeModule32 from "../api/v1/proposals/manage/[token]/speakers/remind";
import * as routeModule33 from "../api/v1/events/[eventSlug]/proposals/resend-speaker-manage-link";
import * as routeModule34 from "../api/v1/events/[eventSlug]/registrations/resend-confirmation";
import * as routeModule35 from "../api/v1/events/[eventSlug]/registrations/resend-manage-link";
import * as routeModule36 from "../api/v1/events/[eventSlug]/registrations/confirm-email";
import * as routeModule37 from "../api/v1/events/[eventSlug]/registrations/confirm-info";
import * as routeModule38 from "../api/v1/admin/events/[eventSlug]/registrations";
import * as routeModule39 from "../api/v1/proposals/speaker/[token]/presentation";
import * as routeModule40 from "../api/v1/admin/proposals/[proposalId]/finalize";
import * as routeModule41 from "../api/v1/admin/proposals/[proposalId]/speakers";
import * as routeModule42 from "../api/v1/registrations/manage/[token]/headshot";
import * as routeModule43 from "../api/v1/admin/email-templates/[key]/activate";
import * as routeModule44 from "../api/v1/admin/email-templates/[key]/versions";
import * as routeModule45 from "../api/v1/admin/events/[eventSlug]/permissions";
import * as routeModule46 from "../api/v1/admin/proposals/[proposalId]/reviews";
import * as routeModule47 from "../api/v1/proposals/speaker/[token]/reminders";
import * as routeModule48 from "../api/v1/admin/events/[eventSlug]/promoters";
import * as routeModule49 from "../api/v1/admin/events/[eventSlug]/proposals";
import * as routeModule50 from "../api/v1/proposals/speaker/[token]/headshot";
import * as routeModule51 from "../api/v1/admin/events/[eventSlug]/settings";
import * as routeModule52 from "../api/v1/admin/forms/[formKey]/submissions";
import * as routeModule53 from "../api/v1/proposals/manage/[token]/speakers";
import * as routeModule54 from "../api/v1/admin/events/[eventSlug]/invites/index";
import * as routeModule55 from "../api/v1/admin/events/[eventSlug]/forms";
import * as routeModule56 from "../api/v1/admin/events/[eventSlug]/terms";
import * as routeModule57 from "../api/v1/admin/users/[userId]/anonymize";
import * as routeModule58 from "../api/v1/admin/events/[eventSlug]/days";
import * as routeModule59 from "../api/v1/admin/users/[userId]/gravatar";
import * as routeModule60 from "../api/v1/admin/users/[userId]/headshot";
import * as routeModule61 from "../api/v1/events/[eventSlug]/speaker-invites";
import * as routeModule62 from "../api/v1/events/[eventSlug]/registrations";
import * as routeModule63 from "../api/v1/events/[eventSlug]/proposals";
import * as routeModule64 from "../api/v1/invites/[token]/decline-info";
import * as routeModule65 from "../api/v1/registrations/manage/[token]";
import * as routeModule66 from "../api/v1/events/[eventSlug]/invites";
import * as routeModule67 from "../api/v1/invites/[token]/reminders";
import * as routeModule68 from "../api/v1/proposals/speaker/[token]";
import * as routeModule69 from "../api/v1/admin/events/[eventSlug]/index";
import * as routeModule70 from "../api/v1/events/[eventSlug]/forms";
import * as routeModule71 from "../api/v1/events/[eventSlug]/terms";
import * as routeModule72 from "../api/v1/og/donation/[session_id]";
import * as routeModule73 from "../api/v1/proposals/manage/[token]";
import * as routeModule74 from "../api/v1/invites/[token]/decline";
import * as routeModule75 from "../api/v1/invites/[token]/accept";
import * as routeModule76 from "../api/v1/admin/forms/[formKey]/index";
import * as routeModule77 from "../api/v1/admin/users/[userId]/index";
import * as routeModule78 from "../api/v1/invites/[token]/info";
import * as routeModule79 from "../api/v1/og/[code]";
import * as routeModule80 from "../donate/r/[code]";
import * as routeModule81 from "../r/[code]";
import * as routeModule82 from "../api/v1/admin/events/[eventSlug]/registrations/[registrationId]/resend-confirmation";
import * as routeModule83 from "../api/v1/admin/events/[eventSlug]/registrations/[registrationId]/regenerate-badge";
import * as routeModule84 from "../api/v1/admin/events/[eventSlug]/registrations/[registrationId]/open-manage";
import * as routeModule85 from "../api/v1/admin/events/[eventSlug]/registrations/[registrationId]/badge-role";
import * as routeModule86 from "../api/v1/admin/events/[eventSlug]/registrations/[registrationId]/admit";
import * as routeModule87 from "../api/v1/admin/events/[eventSlug]/invites/[inviteId]/resend";
import * as routeModule88 from "../api/v1/admin/events/[eventSlug]/registrations/[registrationId]/index";
import * as routeModule89 from "../api/v1/admin/proposals/[proposalId]/reviews/[reviewId]";
import * as routeModule90 from "../api/v1/admin/events/[eventSlug]/permissions/[permId]";
import * as routeModule91 from "../api/v1/headshots/[userId]/[file]";

export interface GeneratedRoute {
  path: string;
  source: string;
  module: RouteModule;
}

// Duplicate route candidates (index.ts preferred):
// - /api/v1/admin/users/:userId => api/v1/admin/users/[userId]/index.ts, api/v1/admin/users/[userId].ts

export const generatedRoutes: GeneratedRoute[] = [
  { path: "/api/v1/admin/email-templates/preview", source: "api/v1/admin/email-templates/preview.ts", module: routeModule1 },
  { path: "/api/v1/admin/events/sync-from-hugo", source: "api/v1/admin/events/sync-from-hugo.ts", module: routeModule2 },
  { path: "/api/v1/internal/email/reset-failed", source: "api/v1/internal/email/reset-failed.ts", module: routeModule3 },
  { path: "/api/v1/admin/donations/promoters", source: "api/v1/admin/donations/promoters.ts", module: routeModule4 },
  { path: "/api/v1/admin/auth/request-link", source: "api/v1/admin/auth/request-link.ts", module: routeModule5 },
  { path: "/api/v1/admin/auth/verify-link", source: "api/v1/admin/auth/verify-link.ts", module: routeModule6 },
  { path: "/api/v1/internal/calendar/rsvp", source: "api/v1/internal/calendar/rsvp.ts", module: routeModule7 },
  { path: "/api/v1/internal/reminders/run", source: "api/v1/internal/reminders/run.ts", module: routeModule8 },
  { path: "/api/v1/internal/retention/run", source: "api/v1/internal/retention/run.ts", module: routeModule9 },
  { path: "/api/v1/admin/donations/sync", source: "api/v1/admin/donations/sync.ts", module: routeModule10 },
  { path: "/api/v1/internal/email/retry", source: "api/v1/internal/email/retry.ts", module: routeModule11 },
  { path: "/api/v1/admin/email/outbox", source: "api/v1/admin/email/outbox.ts", module: routeModule12 },
  { path: "/api/v1/internal/jobs/run", source: "api/v1/internal/jobs/run.ts", module: routeModule13 },
  { path: "/api/v1/admin/email-templates", source: "api/v1/admin/email-templates.ts", module: routeModule14 },
  { path: "/api/v1/donations/checkout", source: "api/v1/donations/checkout.ts", module: routeModule15 },
  { path: "/api/v1/donations/promoter", source: "api/v1/donations/promoter.ts", module: routeModule16 },
  { path: "/api/v1/donations/session", source: "api/v1/donations/session.ts", module: routeModule17 },
  { path: "/api/v1/admin/donations", source: "api/v1/admin/donations.ts", module: routeModule18 },
  { path: "/api/v1/webhooks/stripe", source: "api/v1/webhooks/stripe.ts", module: routeModule19 },
  { path: "/api/v1/admin/events", source: "api/v1/admin/events.ts", module: routeModule20 },
  { path: "/api/v1/admin/stats", source: "api/v1/admin/stats.ts", module: routeModule21 },
  { path: "/api/v1/admin/users", source: "api/v1/admin/users.ts", module: routeModule22 },
  { path: "/api/v1/geo", source: "api/v1/geo.ts", module: routeModule23 },
  { path: "/api/v1", source: "api/v1/index.ts", module: routeModule24 },
  { path: "/api", source: "api/index.ts", module: routeModule25 },
  { path: "/api/v1/admin/events/:eventSlug/invites/attendees/preview", source: "api/v1/admin/events/[eventSlug]/invites/attendees/preview.ts", module: routeModule26 },
  { path: "/api/v1/admin/events/:eventSlug/emails/campaign/preview", source: "api/v1/admin/events/[eventSlug]/emails/campaign/preview.ts", module: routeModule27 },
  { path: "/api/v1/admin/events/:eventSlug/invites/attendees/bulk", source: "api/v1/admin/events/[eventSlug]/invites/attendees/bulk.ts", module: routeModule28 },
  { path: "/api/v1/admin/events/:eventSlug/invites/speakers/bulk", source: "api/v1/admin/events/[eventSlug]/invites/speakers/bulk.ts", module: routeModule29 },
  { path: "/api/v1/admin/events/:eventSlug/emails/campaign/send", source: "api/v1/admin/events/[eventSlug]/emails/campaign/send.ts", module: routeModule30 },
  { path: "/api/v1/admin/events/:eventSlug/waitlist/promote", source: "api/v1/admin/events/[eventSlug]/waitlist/promote.ts", module: routeModule31 },
  { path: "/api/v1/proposals/manage/:token/speakers/remind", source: "api/v1/proposals/manage/[token]/speakers/remind.ts", module: routeModule32 },
  { path: "/api/v1/events/:eventSlug/proposals/resend-speaker-manage-link", source: "api/v1/events/[eventSlug]/proposals/resend-speaker-manage-link.ts", module: routeModule33 },
  { path: "/api/v1/events/:eventSlug/registrations/resend-confirmation", source: "api/v1/events/[eventSlug]/registrations/resend-confirmation.ts", module: routeModule34 },
  { path: "/api/v1/events/:eventSlug/registrations/resend-manage-link", source: "api/v1/events/[eventSlug]/registrations/resend-manage-link.ts", module: routeModule35 },
  { path: "/api/v1/events/:eventSlug/registrations/confirm-email", source: "api/v1/events/[eventSlug]/registrations/confirm-email.ts", module: routeModule36 },
  { path: "/api/v1/events/:eventSlug/registrations/confirm-info", source: "api/v1/events/[eventSlug]/registrations/confirm-info.ts", module: routeModule37 },
  { path: "/api/v1/admin/events/:eventSlug/registrations", source: "api/v1/admin/events/[eventSlug]/registrations.ts", module: routeModule38 },
  { path: "/api/v1/proposals/speaker/:token/presentation", source: "api/v1/proposals/speaker/[token]/presentation.ts", module: routeModule39 },
  { path: "/api/v1/admin/proposals/:proposalId/finalize", source: "api/v1/admin/proposals/[proposalId]/finalize.ts", module: routeModule40 },
  { path: "/api/v1/admin/proposals/:proposalId/speakers", source: "api/v1/admin/proposals/[proposalId]/speakers.ts", module: routeModule41 },
  { path: "/api/v1/registrations/manage/:token/headshot", source: "api/v1/registrations/manage/[token]/headshot.ts", module: routeModule42 },
  { path: "/api/v1/admin/email-templates/:key/activate", source: "api/v1/admin/email-templates/[key]/activate.ts", module: routeModule43 },
  { path: "/api/v1/admin/email-templates/:key/versions", source: "api/v1/admin/email-templates/[key]/versions.ts", module: routeModule44 },
  { path: "/api/v1/admin/events/:eventSlug/permissions", source: "api/v1/admin/events/[eventSlug]/permissions.ts", module: routeModule45 },
  { path: "/api/v1/admin/proposals/:proposalId/reviews", source: "api/v1/admin/proposals/[proposalId]/reviews.ts", module: routeModule46 },
  { path: "/api/v1/proposals/speaker/:token/reminders", source: "api/v1/proposals/speaker/[token]/reminders.ts", module: routeModule47 },
  { path: "/api/v1/admin/events/:eventSlug/promoters", source: "api/v1/admin/events/[eventSlug]/promoters.ts", module: routeModule48 },
  { path: "/api/v1/admin/events/:eventSlug/proposals", source: "api/v1/admin/events/[eventSlug]/proposals.ts", module: routeModule49 },
  { path: "/api/v1/proposals/speaker/:token/headshot", source: "api/v1/proposals/speaker/[token]/headshot.ts", module: routeModule50 },
  { path: "/api/v1/admin/events/:eventSlug/settings", source: "api/v1/admin/events/[eventSlug]/settings.ts", module: routeModule51 },
  { path: "/api/v1/admin/forms/:formKey/submissions", source: "api/v1/admin/forms/[formKey]/submissions.ts", module: routeModule52 },
  { path: "/api/v1/proposals/manage/:token/speakers", source: "api/v1/proposals/manage/[token]/speakers.ts", module: routeModule53 },
  { path: "/api/v1/admin/events/:eventSlug/invites", source: "api/v1/admin/events/[eventSlug]/invites/index.ts", module: routeModule54 },
  { path: "/api/v1/admin/events/:eventSlug/forms", source: "api/v1/admin/events/[eventSlug]/forms.ts", module: routeModule55 },
  { path: "/api/v1/admin/events/:eventSlug/terms", source: "api/v1/admin/events/[eventSlug]/terms.ts", module: routeModule56 },
  { path: "/api/v1/admin/users/:userId/anonymize", source: "api/v1/admin/users/[userId]/anonymize.ts", module: routeModule57 },
  { path: "/api/v1/admin/events/:eventSlug/days", source: "api/v1/admin/events/[eventSlug]/days.ts", module: routeModule58 },
  { path: "/api/v1/admin/users/:userId/gravatar", source: "api/v1/admin/users/[userId]/gravatar.ts", module: routeModule59 },
  { path: "/api/v1/admin/users/:userId/headshot", source: "api/v1/admin/users/[userId]/headshot.ts", module: routeModule60 },
  { path: "/api/v1/events/:eventSlug/speaker-invites", source: "api/v1/events/[eventSlug]/speaker-invites.ts", module: routeModule61 },
  { path: "/api/v1/events/:eventSlug/registrations", source: "api/v1/events/[eventSlug]/registrations.ts", module: routeModule62 },
  { path: "/api/v1/events/:eventSlug/proposals", source: "api/v1/events/[eventSlug]/proposals.ts", module: routeModule63 },
  { path: "/api/v1/invites/:token/decline-info", source: "api/v1/invites/[token]/decline-info.ts", module: routeModule64 },
  { path: "/api/v1/registrations/manage/:token", source: "api/v1/registrations/manage/[token].ts", module: routeModule65 },
  { path: "/api/v1/events/:eventSlug/invites", source: "api/v1/events/[eventSlug]/invites.ts", module: routeModule66 },
  { path: "/api/v1/invites/:token/reminders", source: "api/v1/invites/[token]/reminders.ts", module: routeModule67 },
  { path: "/api/v1/proposals/speaker/:token", source: "api/v1/proposals/speaker/[token].ts", module: routeModule68 },
  { path: "/api/v1/admin/events/:eventSlug", source: "api/v1/admin/events/[eventSlug]/index.ts", module: routeModule69 },
  { path: "/api/v1/events/:eventSlug/forms", source: "api/v1/events/[eventSlug]/forms.ts", module: routeModule70 },
  { path: "/api/v1/events/:eventSlug/terms", source: "api/v1/events/[eventSlug]/terms.ts", module: routeModule71 },
  { path: "/api/v1/og/donation/:session_id", source: "api/v1/og/donation/[session_id].ts", module: routeModule72 },
  { path: "/api/v1/proposals/manage/:token", source: "api/v1/proposals/manage/[token].ts", module: routeModule73 },
  { path: "/api/v1/invites/:token/decline", source: "api/v1/invites/[token]/decline.ts", module: routeModule74 },
  { path: "/api/v1/invites/:token/accept", source: "api/v1/invites/[token]/accept.ts", module: routeModule75 },
  { path: "/api/v1/admin/forms/:formKey", source: "api/v1/admin/forms/[formKey]/index.ts", module: routeModule76 },
  { path: "/api/v1/admin/users/:userId", source: "api/v1/admin/users/[userId]/index.ts", module: routeModule77 },
  { path: "/api/v1/invites/:token/info", source: "api/v1/invites/[token]/info.ts", module: routeModule78 },
  { path: "/api/v1/og/:code", source: "api/v1/og/[code].ts", module: routeModule79 },
  { path: "/donate/r/:code", source: "donate/r/[code].ts", module: routeModule80 },
  { path: "/r/:code", source: "r/[code].ts", module: routeModule81 },
  { path: "/api/v1/admin/events/:eventSlug/registrations/:registrationId/resend-confirmation", source: "api/v1/admin/events/[eventSlug]/registrations/[registrationId]/resend-confirmation.ts", module: routeModule82 },
  { path: "/api/v1/admin/events/:eventSlug/registrations/:registrationId/regenerate-badge", source: "api/v1/admin/events/[eventSlug]/registrations/[registrationId]/regenerate-badge.ts", module: routeModule83 },
  { path: "/api/v1/admin/events/:eventSlug/registrations/:registrationId/open-manage", source: "api/v1/admin/events/[eventSlug]/registrations/[registrationId]/open-manage.ts", module: routeModule84 },
  { path: "/api/v1/admin/events/:eventSlug/registrations/:registrationId/badge-role", source: "api/v1/admin/events/[eventSlug]/registrations/[registrationId]/badge-role.ts", module: routeModule85 },
  { path: "/api/v1/admin/events/:eventSlug/registrations/:registrationId/admit", source: "api/v1/admin/events/[eventSlug]/registrations/[registrationId]/admit.ts", module: routeModule86 },
  { path: "/api/v1/admin/events/:eventSlug/invites/:inviteId/resend", source: "api/v1/admin/events/[eventSlug]/invites/[inviteId]/resend.ts", module: routeModule87 },
  { path: "/api/v1/admin/events/:eventSlug/registrations/:registrationId", source: "api/v1/admin/events/[eventSlug]/registrations/[registrationId]/index.ts", module: routeModule88 },
  { path: "/api/v1/admin/proposals/:proposalId/reviews/:reviewId", source: "api/v1/admin/proposals/[proposalId]/reviews/[reviewId].ts", module: routeModule89 },
  { path: "/api/v1/admin/events/:eventSlug/permissions/:permId", source: "api/v1/admin/events/[eventSlug]/permissions/[permId].ts", module: routeModule90 },
  { path: "/api/v1/headshots/:userId/:file", source: "api/v1/headshots/[userId]/[file].ts", module: routeModule91 },
];
