const domains = {
  membership: "Membership",
  identities: "Identities",
  events: "Events",
  groups: "Groups",
  "email-templates": "Email templates",
  forms: "Forms",
  email: "Email",
  donations: "Donations",
  users: "Users",
  audit: "Audit",
  analytics: "Analytics",
  retention: "Retention",
  scheduler: "Scheduler",
  access: "Access permissions",
  organizations: "Organizations",
  sponsorships: "Sponsorships",
  votes: "Votes",
  proposals: "Proposals",
  agenda: "Agenda",
  admin: "Administration",
} as const;
function metadata(domain: keyof typeof domains, actionLabel: string, access: "read" | "write") {
  return { domain, domainLabel: domains[domain], actionLabel, access };
}

/**
 * Canonical permission definitions supply the schema vocabulary and consent UI.
 * D1 stores role assignments and approved grants, not another metadata catalog.
 * Actions such as approve, anonymize, or synchronize are writes.
 */
export const PERMISSION_METADATA = {
  "membership:read": metadata("membership", "Read", "read"),
  "membership:write": metadata("membership", "Create and edit", "write"),
  "identities:activate": metadata("identities", "Activate", "write"),
  "membership:approve": metadata("membership", "Approve", "write"),
  "events:read": metadata("events", "Read", "read"),
  "events:write": metadata("events", "Create and edit", "write"),
  "events:manage": metadata("events", "Manage", "write"),
  "groups:read": metadata("groups", "Read", "read"),
  "groups:write": metadata("groups", "Create and edit", "write"),
  "email-templates:read": metadata("email-templates", "Read", "read"),
  "email-templates:write": metadata("email-templates", "Create and edit", "write"),
  "email-templates:manage": metadata("email-templates", "Manage", "write"),
  "forms:read": metadata("forms", "Read", "read"),
  "forms:write": metadata("forms", "Create and edit", "write"),
  "email:read": metadata("email", "Read", "read"),
  "email:manage": metadata("email", "Manage", "write"),
  "donations:read": metadata("donations", "Read", "read"),
  "donations:sync": metadata("donations", "Synchronize", "write"),
  "users:read": metadata("users", "Read", "read"),
  "users:write": metadata("users", "Create and edit", "write"),
  "users:anonymize": metadata("users", "Anonymize", "write"),
  "audit:read": metadata("audit", "Read", "read"),
  "analytics:read": metadata("analytics", "Read", "read"),
  "retention:read": metadata("retention", "Read", "read"),
  "retention:run": metadata("retention", "Run", "write"),
  "scheduler:read": metadata("scheduler", "Read", "read"),
  "scheduler:manage": metadata("scheduler", "Manage", "write"),
  "access:grant": metadata("access", "Grant", "write"),
  "access:revoke": metadata("access", "Revoke", "write"),
  "organizations:read": metadata("organizations", "Read", "read"),
  "organizations:write": metadata("organizations", "Create and edit", "write"),
  "organizations:content-review": metadata("organizations", "Review content", "write"),
  "sponsorships:read": metadata("sponsorships", "Read", "read"),
  "sponsorships:write": metadata("sponsorships", "Create and edit", "write"),
  "votes:create": metadata("votes", "Create", "write"),
  "votes:manage": metadata("votes", "Manage", "write"),
  "proposals:read": metadata("proposals", "Read", "read"),
  "proposals:score": metadata("proposals", "Score", "write"),
  "proposals:manage": metadata("proposals", "Manage", "write"),
  "proposals:edit_accepted_abstract": metadata("proposals", "Edit accepted abstracts", "write"),
  "proposals:cancel_accepted": metadata("proposals", "Cancel accepted proposals", "write"),
  "agenda:read": metadata("agenda", "Read", "read"),
  "agenda:write": metadata("agenda", "Create and edit", "write"),
  "admin:read": metadata("admin", "Read", "read"),
  "admin:write": metadata("admin", "Create and edit", "write"),
};
